### ISSUE TITLE
Add app template / more commands

### ISSUE THREAD

**Issue by nanu-c** [bhdouglass/clickable#21] opened 2017-12-18 11:23 UTC
It would be nice to have a hello-world template with just 
`clickable init ./`
to put in place ./ that could be installed.

Then I propose another command like 

`clickable run` that does something like `clickable kill build click_build install launch` :)

**Comment by bhdouglass** [comment] 2017-12-18 15:00
Yes, adding template support is already planned! (duplicate of #19). Until then you can use this template: https://github.com/bhdouglass/ut-app-template

Actually clickable already does that, it's just `clickable` without any arguments to run the default set which is `kill clean build click-build install launch`.

**Closed by bhdouglass** 2017-12-18 15:00 UTC
